apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: manojsinghdocker/my-web-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_MODE
          value: "production"
        - name: DB_HOST
          value: "db.example.com"
